apiVersion: 1
prune: true

datasources:
  - name: timescaleDB
    type: postgres
    access: proxy
    orgId: 1
    uid: timescaleDB
    url: database:5432
    user: ${POSTGRES_USER}
    isDefault: true
    jsonData:
      connMaxLifetime: 14400
      database: ${POSTGRES_DB}
      maxIdleConns: 100
      maxIdleConnsAuto: true
      maxOpenConns: 100
      postgresVersion: 1300
      sslmode: disable
      timescaledb: true
    secureJsonData:
      password: ${POSTGRES_PASSWORD}
    version: 1
    editable: true