{
 "title": "The Boring Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "device_ID",
    "label": "device_id",
    "query": "select distinct device_id from telemetry "
   },
   {
    "name": "measurements",
    "label": "measurements",
    "query": "select distinct name from telemetry where device_id = ${device_ID}"
   }
  ]
 },
 "panels": [
  {
   "title": "Devices",
   "type": "table",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "select distinct device_id from telemetry "
    }
   ]
  },
  {
   "title": "measurement types",
   "type": "table",
   "gridPos": { "h": 7, "w": 3, "x": 6, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT distinct name from telemetry"
    }
   ]
  },
  { "title": "Real time current measurements", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "${measurements}",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 8 },
   "repeat": "measurements",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT cast(value as integer) FROM telemetry WHERE device_id = ${device_ID} AND name = '${measurements}' and $__timeFilter(timestamp) \r\nORDER BY \"timestamp\" ASC "
    }
   ]
  },
  { "title": "Historic data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "measurements",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "rawSql": "SELECT \r\n  DATE_TRUNC('second', t.\"timestamp\") AS \"time\",\r\n  cast(temp.value as integer) AS \"temperature\",\r\n  cast(press.value as integer) AS \"pressure\",\r\n  cast(humid.value as integer) AS \"humidity\"\r\nFROM \r\n  (SELECT DISTINCT DATE_TRUNC('second', \"timestamp\") AS \"timestamp\" FROM telemetry WHERE device_id = ${device_ID}) t\r\nJOIN \r\n  (SELECT DATE_TRUNC('second', \"timestamp\") AS \"timestamp\", value FROM telemetry WHERE device_id = ${device_ID} AND name = 'temperature') temp\r\n  ON t.\"timestamp\" = temp.\"timestamp\"\r\nJOIN \r\n  (SELECT DATE_TRUNC('second', \"timestamp\") AS \"timestamp\", value FROM telemetry WHERE device_id = ${device_ID} AND name = 'pressure') press\r\n  ON t.\"timestamp\" = press.\"timestamp\"\r\nJOIN \r\n  (SELECT DATE_TRUNC('second', \"timestamp\") AS \"timestamp\", value FROM telemetry WHERE device_id = ${device_ID} AND name = 'humidity') humid\r\n  ON t.\"timestamp\" = humid.\"timestamp\"\r\nWHERE $__timeFilter(t.\"timestamp\")"
    }
   ]
  }
 ]
}